language: java
jdk:
- oraclejdk8
addons:
  sonarqube:
    branches:
      - dev
      - master
    organization: "bytekeeper-github"
    token:
      secure: "I4h52nLHQP+is/knbKyAXmuzQZBIz99IKD2HJota1IrAkpj1uVikca0UtTWu9SQnGdD/sOV2xgVbIP0kUlAVHSlOHXfSEdGLxP5ix49Yo+si8nvaSKsQPaIXsPF2De98+qyHasvYOhawUcMctR6+FWtxwj0hymAgNWQXnVKK1lQ="
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
env:
- secure: Nyb7rKKSkUQRZfk84UvAG1XxqA6Ze3iHZ3BQ5FVI4K92tRMXzjwPBVG7hPzkHWFgXkRqhlW6XkSXmGHQBJ+8bKJ9X9dNcviuEx65oDDzv7SoEm+mMP4sTVwQyv62lkv2zKQ9rG/xRX2ElElPrT6keS3ssVwuldhLpKwyXw8cJ0U=
- 
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- ./gradlew check sonarqube release --stacktrace
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Wy/mCFejLqMLLCJ5xdsQbKDKYO7LcXzWhaUI0iBtYNmV+xZgXLkLWNhdcVGuP7fBtMSztbKNeTpWbYYVS6AfE1NIlLusANBJi0FsRV14CfqzlDyRgdvg3Xkf1UAT889z3Y4prxrUJHwQN2yAZ3LTUGXAZeG+2xzHM6yKbZO8clU=
  file_glob: true
  file: build/libs/*
  on:
    repo: SimpleTimeTracking/StandaloneClient
    tags: true
